In [4]:
import ccxt
import pandas as pd
import numpy as np
from datetime import datetime

In [5]:
class CryptoDataCollector:

    def __init__(self, exchanges=['binanceus', 'coinbase', 'kraken', 'bitfinex', 
                                'kucoin', 'okx', 'gateio', 'bitstamp', 
                            'poloniex', 'huobi', 'hitbtc', 'bitget', 'exmo', 'phemex', 'upbit']):
        self.exchanges = [getattr(ccxt, ex)() for ex in exchanges]
        
    def fetch_historical_data(self, symbol='BTC/USDT', timeframe='5m', limit=10000):
        data = []
        for exchange in self.exchanges:
            ohlcv = exchange.fetch_ohlcv(symbol, timeframe, limit=limit)
            df = pd.DataFrame(ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
            df['timestamp'] = df['timestamp'].apply(lambda x: datetime.fromtimestamp(x / 1000))
            df['exchange'] = exchange.id
            data.append(df)
        return pd.concat(data)

    def fetch_social_sentiment(self, symbol):
        # Implement API calls to social sentiment sources
        # Could use Twitter API, Reddit API, etc.
        pass

In [6]:
btc_price=CryptoDataCollector().fetch_historical_data()

In [11]:
btc_price['timestamp'] = pd.to_datetime(btc_price['timestamp'])
btc_price.to_csv('btc_data.csv',  index=False, date_format='%Y-%m-%d %H:%M:%S')

In [12]:
df_read = pd.read_csv('btc_data.csv', parse_dates=['timestamp'])

In [13]:
df_read

,timestamp,open,high,low,close,volume,exchange
0,2024-11-23 12:40:00,97391.90,97619.05,97391.90,97619.05,0.017180,binanceus
1,2024-11-23 12:45:00,97619.04,97619.05,97598.91,97598.92,0.022130,binanceus
2,2024-11-23 12:50:00,97690.74,97690.74,97564.11,97676.36,0.213960,binanceus
3,2024-11-23 12:55:00,97564.70,97702.49,97564.70,97702.49,0.011000,binanceus
4,2024-11-23 13:00:00,97703.00,97703.01,97613.34,97703.01,0.001140,binanceus
...,...,...,...,...,...,...,...
23512,2024-11-26 23:25:00,93168.04,93168.04,93010.57,93010.57,0.012495,upbit
23513,2024-11-26 23:30:00,93441.06,93441.26,93037.86,93441.26,0.064005,upbit
23514,2024-11-26 23:35:00,93441.26,93441.26,93441.26,93441.26,0.027900,upbit
23515,2024-11-26 23:40:00,93441.26,93441.26,93093.75,93419.58,0.167994,upbit
23516,2024-11-26 23:55:00,93419.58,93746.55,92879.85,92879.85,0.050066,upbit

In [14]:
btc_price

,timestamp,open,high,low,close,volume,exchange
0,2024-11-23 12:40:00,97391.90,97619.05,97391.90,97619.05,0.017180,binanceus
1,2024-11-23 12:45:00,97619.04,97619.05,97598.91,97598.92,0.022130,binanceus
2,2024-11-23 12:50:00,97690.74,97690.74,97564.11,97676.36,0.213960,binanceus
3,2024-11-23 12:55:00,97564.70,97702.49,97564.70,97702.49,0.011000,binanceus
4,2024-11-23 13:00:00,97703.00,97703.01,97613.34,97703.01,0.001140,binanceus
...,...,...,...,...,...,...,...
195,2024-11-26 23:25:00,93168.04,93168.04,93010.57,93010.57,0.012495,upbit
196,2024-11-26 23:30:00,93441.06,93441.26,93037.86,93441.26,0.064005,upbit
197,2024-11-26 23:35:00,93441.26,93441.26,93441.26,93441.26,0.027900,upbit
198,2024-11-26 23:40:00,93441.26,93441.26,93093.75,93419.58,0.167994,upbit
199,2024-11-26 23:55:00,93419.58,93746.55,92879.85,92879.85,0.050066,upbit